name: rrte
favicon: null
layout_spectrum: 0.1755905777681619
typography_spectrum: 0.998526023235172
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.36205768631771207
  lightness: 0.951258348999545
  saturation: 0.104090845445171
  rhythmicContrast: 0.8277235685382038
purpose: []
